language: csharp
solution: ArchiSteamFarm.sln
git:
  depth: 10
mono:
- weekly
- latest
matrix:
  allow_failures:
  - mono: weekly
before_script:
- source mono_envsetup.sh
notifications:
  email: false
deploy:
  provider: releases
  file:
  - $TRAVIS_BUILD_DIR/bin/release/ASF.exe
  - $TRAVIS_BUILD_DIR/out/ASF-ConfigGenerator.exe
  - $TRAVIS_BUILD_DIR/out/asf.exe ASF-Service.exe
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: n2RxPIY0nEOLyPHMM/0iFQYozfceSPkf7jNEkHo3i5km7KyBZPqn9ALLInnruRaXWbexOSqQ0gIoETifkpO6gVMkKNlQaM+BjipgKpbGgnWRUfFtcVrfkZsLDgKKp4cfRNa9Xbu8KL5iBS6O5VrFW660InSa+/isxvpwZJh9e4eVW3VAmR2YxU1BL0SP+M4A+p4RlJBxsfkcmj96xs2PK6MdtjYLr7Xo+iG+Hidbh2+4pDFvbcur2HEeFMgy7OFumnotqqliyf65V+GCZ5qFe56q52Twf/Oty2fYVuqP5k0ssGsDAp90jFIlRAAKKw+7fy0ca8CBsXC6WXptmbHBRanGYpUUfotGDp3CJzSjEPM4Swud6M/kIBSk9UVaSROY25HUxzVWIGqu8d8lbxfEbYZynNbY8eVwWiUfjzUNTMNYN4nrrtgEGRZSleQb4CauCquM6EHXmkdOHKjJCqkVhoZG7Cq48fxZr77AwxU2v8Zn95ijkorRL4/kfd819VupBxvgrcCI4mxEbgP165bCVAMgMcHk3CvnKr9wkIHXO1zmoJhzkGjpYuLTh/oI9Lj6nK+4WsHpY/E04TGKUXubZS/9bJTZaCthHdQs9uAYkWBuycDM4TdP8y1ZQZ/epkNvMNQFgIR7CsAdaAUm8u4Q/c1IjdyjSwK4cRM/Yam+g+E=
