version: 1.0.{build}-{branch}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_depth: 10
build:
  project: ArchiSteamFarm.sln
  parallel: true
  verbosity: minimal

  artifacts:
  - path: out\ASF.EXE
    name: ASF.exe
  - path: out\ASF-ConfigGenerator.EXE
	name: ASF-ConfigGenerator.exe
  - path: 'out\config\*'
    name: config