version: #{build}-{branch}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_depth: 10
max_jobs: 2

build:
  project: ArchiSteamFarm.sln
  parallel: true
  verbosity: minimal

branches:
  only:
    - master

after_build:
    - 7z a out\ASF.ZIP out\config\*
    - 7z a out\ASF.zip out\ASF-Service.exe
    - 7z a out\ASF.zip out\ASF.EXE

artifacts:
  - path: out\ASF.EXE
    name: ASF.exe

  - path: out\ASF-Service.EXE
    name: ASF-Service.exe

  - path: out\ASF.zip
    name: ASF.ZIP

skip_non_tags: true

deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  artifact: ASF.ZIP,ASF.exe,ASF-Service.exe
  auth_token: 
    secure: H9EylqWwP3brlY6UGlVdO88iY+EXE9zCNcmU3XtLeMMqWlY5lmAtr2OA6J1xncd+
  draft: false
  prerelease: false
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only
