"preserve_hierarchy": true
files:
  - source: /ArchiSteamFarm/Localization/Strings.resx
    translation: /ArchiSteamFarm/Localization/Strings.%locale%.resx
  - source: /docs/WebConfigGenerator/src/locale/strings.json
    translation: /docs/WebConfigGenerator/src/locale/%locale%.json
